source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Interaction-Gaming/ig-private-podspec.git'

# platform :ios, '11.0'

target 'MobilePlayslips' do
  use_frameworks!
  pod 'lottie-ios', '~> 3.1.9'
  pod 'LottoLog', '~> 1.1.0'
  pod 'ReSwift',  '~> 5.0.0'
  pod 'UIColor_Hex_Swift','~> 5.1.0'
end
